.github/workflows/publish-shesha-reactjs-0.x.x.yml
shesha-reactjs/package.json

updates to the package.json to trigger a test build

fix(meta): package update

---

shesha-reactjs/package.json

test the update that triggers the on pull request merge action

fix(workflow): test fix trigger on merge

---

shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host/test.md

testing pr's

---

shesha-core/src/Shesha.NHibernate/NHibernate/Maps/Conventions.cs
shesha-core/src/Shesha.Web.FormsDesigner/Domain/FormConfiguration.cs
shesha-reactjs/src/providers/formPersisterProvider/index.tsx

removed formatting of the markup in the react library

enabled lazy loading of forms markup

---

shesha-starter/testing.md

Test 1 - Checking why PR sometime do work

---

shesha-functional-tests/adminportal/src/pages/_app.tsx

refactor: shesha-functional-test adminin portal

---

shesha-reactjs/src/components/formDesigner/components/imageAnnotation/descriptionList.tsx
shesha-reactjs/src/components/formDesigner/components/imageAnnotation/imageAnnotation.tsx
shesha-reactjs/src/components/formDesigner/components/imageAnnotation/styles/index.less

Here I was fixing extra scroll bar on the description container

styling adjustments for scrolling

---

shesha-reactjs/src/components/formDesigner/components/refListStatus/components/control.tsx
shesha-reactjs/tsconfig.json

corrected the import path

---

.github/workflows/publish-nuget-npm.yml

updated node version in the workflow

chore: updated npm workflow

---

shesha-functional-tests/backend/src/Module/Boxfusion.SheshaFunctionalTests.Common.Domain/Domain/Account.cs
shesha-functional-tests/backend/src/Module/Boxfusion.SheshaFunctionalTests.Common.Domain/Domain/EmployeeAccount.cs
shesha-functional-tests/backend/src/Module/Boxfusion.SheshaFunctionalTests.Common.Domain/Migrations/M20230411130200.cs

Getting error because account entity was conflicting with account on shesha core

update account entity

---

shesha-functional-tests/adminportal/public/static/config/web.config.js
shesha-reactjs/src/components/formDesigner/components/address/settings.tsx

adding label alignmnet to the address component

Label alignment for address

---

shesha-reactjs/src/components/dataTable/cell/dataCell.tsx
shesha-reactjs/src/components/dataTable/index.tsx
shesha-reactjs/src/components/reactTable/index.tsx
shesha-reactjs/src/components/reactTable/interfaces.ts
shesha-reactjs/src/components/reactTable/newTableRowEditor.tsx
shesha-reactjs/src/components/reactTable/tableRow.tsx
shesha-reactjs/src/designer-components/dataTable/table/tableComponent-settings.tsx
shesha-reactjs/src/designer-components/entityReference/entityReference.tsx
shesha-reactjs/src/providers/crudContext/index.tsx

fixed visibility of the display components in the datatables

fixed link to metadata in the entityReference

---

shesha-reactjs/src/components/timeline/index.tsx

Feat : sort timeline data

---

shesha-reactjs/src/pages/dynamic/index.tsx

when formWithData.loadingState === 'loading'
this way it gets executed once per change if available

fix(onInitialized): sometimes onInitialized is not ready 

---

shesha-reactjs/src/components/formDesigner/components/checkboxGroup/multiCheckbox.tsx
shesha-reactjs/src/components/formDesigner/components/radio/radioGroup.tsx

Array.isArray(data?.result) was not returning an array because the apis usually return array inside data.result.items

fix(CheckboxGroup:url): data now passed to reducerFunc as an array

---

shesha-reactjs/src/components/formDesigner/components/subForm/componentsContainerSubForm.tsx
shesha-reactjs/src/components/formDesigner/containers/componentsContainerForm.tsx
shesha-reactjs/src/providers/subForm/index.tsx

Components wrapped in container were losing their alignment because ComponentsContainerSubForm was not wrapping the child components within the container

fix(ComponentsContainerSubForm): wrapped the components with div

---

shesha-reactjs/src/components/dataList/index.tsx
shesha-reactjs/src/components/dataList/models.tsx
shesha-reactjs/src/components/formDesigner/components/dataList/dataListComponent.tsx
shesha-reactjs/src/components/formDesigner/components/dataList/dataListSettings.tsx

User Story 48427: Add a functionality to allow sorting on the Datalist component

User Story 50239: Support for Drill-down Action on DataList component

---

shesha-core/src/Shesha.FluentMigrator/FluentMigrator/ReferenceLists/ReferenceListDbHelper.cs
shesha-core/src/Shesha.FluentMigrator/FluentMigrator/Tags.cs
shesha-core/src/Shesha.Framework/Domain/Attributes/DiscriminatorAttribute.cs
shesha-core/src/Shesha.Framework/Domain/MappingHelper.cs
shesha-core/src/Shesha.Framework/Migrations/PostgreSql/M20230921150099.cs

-fix: PostgreSql support in the ReferenceListDbHelper
-fix: changed Person.FullName property to calculated on PostgreSql

-feat: implemented support of snake_case in for the discriminator column

---

shesha-reactjs/rollup.config.mjs
shesha-reactjs/src/components/autocomplete/index.stories.tsx
shesha-reactjs/src/components/entityPicker/index.tsx
shesha-reactjs/src/components/entityPicker/styles/index.less
shesha-reactjs/src/components/formComponentSelector/index.stories.tsx
shesha-reactjs/src/components/formDesigner/components/codeEditor/interfaces.ts
shesha-reactjs/src/components/formDesigner/components/drawer/drawer.tsx
shesha-reactjs/src/designer-components/refListStatus/components/control.tsx
shesha-reactjs/src/hooks/useGet.ts
shesha-reactjs/src/providers/form/models.ts
shesha-reactjs/src/utils/entity.ts

-fix: fixed reaction of the useGet on change of the queryString
-chore: reconfigured build to fail on typescript errors
-fix: fixed typescript errors
-fix: added optional id property to the ICodeEditorProps
-fix: fixed text in the EntityPicker
-feat: added a hint to the EntityPicker

-fix: IFormComponentContainer.id marked mandatory

---

shesha-reactjs/src/providers/dataTable/contexts.ts
shesha-reactjs/src/providers/dataTable/index.tsx

-fix: 51000 The property "Default Page Size" on "DataTable Context" is not working for the "DataTable"

-fix: 51000

---

shesha-reactjs/src/providers/dataTable/index.tsx

-fix: fixed data fetching in the table when filters stay unchanged first evaluation

-fix: fixed data fetching in the table when filters stay unchanged first evaluation

---

shesha-reactjs/src/components/reactTable/index.tsx

-fix: 50975 Misalignment of "Add Inline" Columns when "Use Multi-Select" is true

-fix: 50975 Misalignment of "Add Inline" Columns when "Use Multi-Select" is true

---

shesha-reactjs/src/components/refListStatus/index.tsx
shesha-reactjs/src/components/refListStatus/tooltip.tsx
shesha-reactjs/src/pages/dynamic/index.stories.tsx

Hi, I  have resolved refListStatus toolTip issue linked to[ this card](https://github.com/shesha-io/shesha-framework/issues/554).

Phumudzo/ref list status/fix

---

shesha-reactjs/src/designer-components/timeField/index.tsx
shesha-reactjs/src/pages/dynamic/index.stories.tsx

This PR aims to address [this issue](https://github.com/shesha-io/shesha-framework/issues/532) . My preliminary findings regarding this issue is that the "timePicker component" is painted to the DOM before the latest values hence "blank" intially and to repaint the DOM I have introduced the key property to the TimePicker to "re-paint". Please review and advise.

delayed time values

---

shesha-reactjs/src/components/formDesigner/components/wizard/hooks.ts
shesha-reactjs/src/components/formDesigner/components/wizard/index.tsx
shesha-reactjs/src/components/formDesigner/components/wizard/utils.ts
shesha-reactjs/src/designer-components/textArea/textArea.tsx

Default active step not functioning properly with JavaScript #625
Text area data display issue in details view #615

Default active step not functioning properly with JavaScript #625

---

shesha-reactjs/src/components/formDesigner/components/richTextEditor/index.tsx
shesha-reactjs/src/components/richTextEditor/index.tsx
shesha-reactjs/src/pages/forms-designer/index.stories.tsx

Hi, This PRb is addressing [this issue](https://github.com/shesha-io/shesha-framework/issues/568).  I didn't do much I just introduced the placeholder to the Jodit's config.

exposing the placeholder property to the richTextEditor

---

shesha-reactjs/src/designer-components/checkbox/checkbox.tsx
shesha-reactjs/src/pages/dynamic/index.stories.tsx

Hi @AlexStepantsov  @hlayisanimazuze  is trying to publish releases/0.28 but while testing she got [this minor bug](https://github.com/shesha-io/shesha-framework/issues/656).  can you please review the fix? if all is well merge it to both main and releases/0.28 .

release 0.28 checkbox fix

---

shesha-core/src/Shesha.Application/NotificationMessages/Dto/NotificationMessageDto.cs
shesha-core/src/Shesha.Application/NotificationMessages/NotificationMessageAppService.cs
shesha-core/src/Shesha.Application/Notifications/Dto/ShaNotificationData.cs
shesha-core/src/Shesha.Application/Notifications/INotificationAppService.cs
shesha-core/src/Shesha.Application/Notifications/NotificationAppService.cs
shesha-core/src/Shesha.Application/Notifications/ShaNotificationDistributer.cs
shesha-core/src/Shesha.Core/Domain/NotificationMessage.cs
shesha-core/src/Shesha.Core/Migrations/M20231128122400.cs

Fixed bug where Recipient is not stored in DB during the sending of an sms, email or push notification.

fix (Notifications) : fixed bug where Recipient is not stored in DB.

---

shesha-reactjs/src/components/dataList/createModal.tsx
shesha-reactjs/src/components/dataList/index.tsx
shesha-reactjs/src/components/dataList/models.tsx
shesha-reactjs/src/components/formDesigner/components/dataList/model.tsx
shesha-reactjs/src/components/formDesigner/components/wizard/hooks.ts

The DataList (and DataList) should be able to bind to and update a list of objects maintained on the front-end #557

Improved support for editing of DataList component in-line with options supported by DataTable #610

---

shesha-reactjs/src/components/dataList/createModal.tsx
shesha-reactjs/src/components/dataList/crudActionButtons.tsx
shesha-reactjs/src/components/dataList/index.tsx
shesha-reactjs/src/components/dataList/itemRenderer.tsx
shesha-reactjs/src/components/formDesigner/components/dataList/dataListControl.tsx
shesha-reactjs/src/components/formDesigner/components/dataList/dataListSettings.tsx
shesha-reactjs/src/designer-components/textField/settingsForm.json
shesha-reactjs/src/providers/dataListCrudContext/actions.ts
shesha-reactjs/src/providers/dataListCrudContext/contexts.tsx
shesha-reactjs/src/providers/dataListCrudContext/index.tsx
shesha-reactjs/src/providers/dataListCrudContext/models.ts
shesha-reactjs/src/providers/dataListCrudContext/reducer.ts
shesha-reactjs/src/providers/form/index.tsx

Data List fails to display File/File List component values and doesn't append entity type #773

Data List Editing: FormData is not logged #749

---

shesha-core/src/Shesha.Framework/Bootstrappers/ReferenceListBootstrapper.cs
shesha-core/src/Shesha.NHibernate/NHibernate/SheshaNHibernateModule.cs
shesha-reactjs/src/components/autocomplete/entityAutocomplete.tsx

skip bootstrappers not registered in the IoC container

---

shesha-reactjs/src/components/formDesigner/configurableFormComponent/dragWrapper.tsx
shesha-reactjs/src/components/formDesigner/configurableFormComponent/index.tsx
shesha-reactjs/src/generic-pages/forms-designer/index.stories.tsx

Hi ,This PR is aimed at addressing [this card](https://github.com/shesha-io/shesha-framework/issues/596). I have moved the delete button to the DragWrapper to enable the button in the same manner as the toolTip of each component independently.

one button at time

---

shesha-reactjs/src/components/formDesigner/components/columns/columnsSettings.tsx
shesha-reactjs/src/components/formDesigner/components/divider/settingsForm.json
shesha-reactjs/src/components/formDesigner/components/drawer/settings.ts
shesha-reactjs/src/components/formDesigner/components/sectionSeprator/settings.ts
shesha-reactjs/src/components/formDesigner/components/sizableColumns/sizableColumnsSettings.tsx
shesha-reactjs/src/components/formDesigner/components/styleBox/components/box.tsx
shesha-reactjs/src/components/formDesigner/components/styleBox/components/input.tsx
shesha-reactjs/src/components/formDesigner/components/styleBox/components/utils.ts
shesha-reactjs/src/components/formDesigner/components/styleBox/index.tsx
shesha-reactjs/src/components/formDesigner/components/styleBox/interfaces.ts
shesha-reactjs/src/components/formDesigner/components/styleBox/settings.ts
shesha-reactjs/src/components/formDesigner/components/styleBox/styles/index.less
shesha-reactjs/src/components/formDesigner/components/tabs/settings.tsx
shesha-reactjs/src/components/formDesigner/components/wizard/settings.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/collapsiblePanelComponent.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json
shesha-reactjs/src/designer-components/container/settingsForm.ts
shesha-reactjs/src/interfaces/toolbarSettings.ts
shesha-reactjs/src/providers/form/defaults/toolboxComponents.ts
shesha-reactjs/src/providers/form/models.ts
shesha-reactjs/src/providers/form/utils.ts
shesha-reactjs/src/utils/string.ts

- Create a component for padding & margin
- Component should be available on the property panel of Layout components
[https://github.com/shesha-io/shesha-framework/issues/857](url)

Box Style for Layout

---

shesha-reactjs/src/components/formDesigner/components/divider/settingsForm.json
shesha-reactjs/src/components/formDesigner/components/drawer/settings.ts
shesha-reactjs/src/components/formDesigner/components/sectionSeprator/settings.ts
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json
shesha-reactjs/src/designer-components/container/settingsForm.ts

- Removed JS tag on property panel for all components

Removed JS tag on StyleBox

---

shesha-core/src/Shesha.Core/Domain/Site.cs
shesha-core/src/Shesha.Core/Migrations/M20240123125400.cs

Updated Site entity, adding ContactNumber column

Entity update

---

shesha-reactjs/src/designer-components/dataTable/table/columnsEditor/columnProperties.tsx
shesha-reactjs/src/designer-components/dataTable/table/entityPickerColumnsEditor/columnProperties.tsx
shesha-reactjs/src/providers/datatableColumnsConfigurator/reducer.ts
shesha-reactjs/src/providers/form/index.tsx
shesha-reactjs/tsconfig.rollup.json

Property name field fails to capture exact typed input #977

Deleting last added column in dataTable breaks system #929

---

shesha-reactjs/src/components/mainLayout/styles/indexStyles.ts

- Primary colour added to button (ant-btn-link)
- [Link](https://github.com/shesha-io/shesha-framework/issues/925)

Added global styling to ant-btn-link

---

shesha-reactjs/src/components/storyBookApp/index.tsx
shesha-reactjs/src/providers/sheshaApplication/index.tsx

- Fixed button link bug
- Changed GlobalSheshaStyles order
- [Link](https://github.com/shesha-io/shesha-framework/issues/925)

Changed GlobalSheshaStyles order

---

shesha-starter/frontend/src/app/app-provider.tsx

- Modified App-provider.tsx file

App-provider.tsx modified

---

shesha-functional-tests/adminportal/.eslintrc.js
shesha-functional-tests/adminportal/package.json
shesha-functional-tests/adminportal/src/app/account/forgot-password/page.tsx
shesha-reactjs/package.json
shesha-reactjs/rollup.config.mjs
shesha-reactjs/src/components/queryBuilder/styles/styles.ts
shesha-reactjs/src/designer-components/_common/styles/listConfiguratorStyles.ts

enabled @typescript-eslint/no-use-before-define linting rule in the shesha-functional-tests/adminportal

css fix: fixed width calculation of the list items

---

shesha-reactjs/src/hooks/index.ts
shesha-reactjs/src/hooks/useNextRouter.ts

- Added useNextRouter hook
- Exposed useNextRouter to hooks index

Added useNextRouter hook

---

shesha-reactjs/package.json
shesha-reactjs/src/hooks/useNextRouter.ts
shesha-reactjs/src/providers/shaRouting/index.tsx

fix: build fix

---

shesha-reactjs/src/components/mainLayout/styles/indexStyles.ts
shesha-reactjs/src/providers/theme/index.tsx

- [Modified Secondary Theme](https://github.com/shesha-io/shesha-framework/issues/925)
- Change baseUrl name on .env
- Added .env to Starter Template

Theme Fix + Config

---

shesha-reactjs/src/components/globalTableFilterBase/styles/styles.ts

-  Primary color border to search bar

feat: added primary color border to search bar

---

shesha-reactjs/src/utils/url.ts

- Allow exposed variable to display correct values
- [Link](https://github.com/shesha-io/shesha-framework/issues/1066)

fix: query variable display

---

shesha-reactjs/src/designer-components/dataTable/pager/settingsForm.ts
shesha-reactjs/src/generic-pages/forms-designer/index.stories.tsx

Hi @AlexStepantsov  . Please assist with this hot fix for release 31. There was a key repeated on dataTable.Pager which resulted in [this issue](https://github.com/shesha-io/shesha-framework/issues/1086). Please assist with merge if all is well to releases/0.31 as well as main . Thanks

duplicate fix

---

shesha-reactjs/src/components/formDesigner/components/sectionSeprator/settings.ts

Hi @AlexStepantsov . Please assist with the review this is similar to the one we had yesterday. Here is the [card](https://github.com/shesha-io/shesha-framework/issues/1091)

guid duplicate resolved

---

shesha-reactjs/src/components/formDesigner/quickEdit/quickEditDialog.tsx
shesha-reactjs/src/generic-pages/dynamic/index.stories.tsx

Hi @AlexStepantsov  please kindly assist with the review regarding [this issue](https://github.com/shesha-io/shesha-framework/issues/878).

width percentage increased

---

shesha-reactjs/src/components/refListStatus/index.tsx
shesha-reactjs/src/components/refListStatus/styles/styles.ts
shesha-reactjs/src/components/refListStatus/tooltip.tsx
shesha-reactjs/src/generic-pages/dynamic/index.stories.tsx

Hi , please kindly assist with this review addressing the issue [here](https://github.com/shesha-io/shesha-framework/issues/1125).

aligning the toolTip

---

shesha-reactjs/src/components/formDesigner/components/passwordCombo/settingsForm.json

Updated the  passwordCombo settingsForm.json file to address the [issue](https://github.com/shesha-io/shesha-framework/issues/1126) of Validation and Style section having the same properties.

fixed typo in settingsForm.json form passwordCombo

---

shesha-functional-tests/publicportal/src/app/app-provider.tsx
shesha-functional-tests/publicportal/src/app/layout.tsx
shesha-functional-tests/publicportal/src/app/login/page.tsx
shesha-functional-tests/publicportal/src/app/login/styles.ts
shesha-functional-tests/publicportal/src/app/shesha/forms-designer/page.tsx
shesha-functional-tests/publicportal/src/app/shesha/layout.tsx
shesha-functional-tests/publicportal/src/app/shesha/settings/page.tsx
shesha-functional-tests/publicportal/src/components/layouts/mainLayout/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/button/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/input/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/input/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/menu/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/title/styles.ts
shesha-functional-tests/publicportal/src/styles/variables.ts

- Styling of Public Portal components
- [Button](https://github.com/shesha-io/shesha-framework/issues/1179)
- [TextArea](https://github.com/shesha-io/shesha-framework/issues/1180)
- [Checkbox](https://github.com/shesha-io/shesha-framework/issues/1185)
- [Wizard](https://github.com/shesha-io/shesha-framework/issues/1185)
- [Tags](https://github.com/shesha-io/shesha-framework/issues/1189)
- [Alerts](https://github.com/shesha-io/shesha-framework/issues/1190)
- [Autocomplete](https://github.com/shesha-io/shesha-framework/issues/1191)

Public Portal Styling

---

shesha-reactjs/src/components/formDesigner/formSettings.json
shesha-starter/frontend/src/app/page.tsx

Addressed broken link [issue](https://github.com/shesha-io/shesha-framework/issues/951)

Broken Link

---

shesha-reactjs/src/components/formDesigner/formSettings.json
shesha-reactjs/src/designer-components/dataTable/tableContext/tableContext.tsx

Addressed this [issue](https://github.com/shesha-io/shesha-framework/issues/560) with regards to dataTableContext showing components even when hidden is set to true

Hidding dataTableContext components when hidden is true 

---

shesha-reactjs/src/components/googlePlacesAutocomplete/index.tsx

Updated the address component to provide multiple suggestion instead of just one as raise in this [issue](https://github.com/shesha-io/shesha-framework/issues/1146)

multiple suggestions on address

---

shesha-reactjs/src/components/formDesigner/components/richTextEditor/index.tsx
shesha-reactjs/src/components/formDesigner/formSettings.json

Update richTextEditor to create the correct element of Enter as raised in [issue](https://github.com/shesha-io/shesha-framework/issues/564).

fix: create specified element on enter

---

shesha-functional-tests/publicportal/src/components/layouts/mainLayout/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/mainLayout/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/menu/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/menu/styles.ts
shesha-reactjs/src/components/panel/index.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/collapsiblePanelComponent.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/interfaces.ts
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json

- Simple Design property added
- Header Background Color property added
- Body Background Color property added
- Radius property added
- [Link](https://github.com/shesha-io/shesha-framework/issues/1159)

feat(collapsiblePanel): added additional properties

---

shesha-reactjs/src/designer-components/card/index.tsx
shesha-reactjs/src/designer-components/card/interfaces.ts
shesha-reactjs/src/designer-components/card/settingsForm.ts
shesha-reactjs/src/providers/form/defaults/toolboxComponents.ts

- Simple Card Component
- Alternative to Collapsible Panel
- [Link](https://github.com/shesha-io/shesha-framework/issues/1188)

Created card component

---

shesha-reactjs/src/components/dropdown/dropdown.tsx
shesha-reactjs/src/designer-components/dateField/datePickerWrapper.tsx

Addressed [issues](https://github.com/shesha-io/shesha-framework/issues/539) related to component not responding to the styling, and [issue](https://github.com/shesha-io/shesha-framework/issues/537) relating to size of datepicker changing when styling is applied.

fix: styling dropdown with any data source 

---

shesha-reactjs/src/designer-components/dateField/datePickerWrapper.tsx

Fixed [issue](https://github.com/shesha-io/shesha-framework/issues/537) of reduced width on datePicker when styling is added

fixed styled datePicker width

---

shesha-reactjs/src/components/mainLayout/styles/styles.ts

Addressing [issue](https://github.com/shesha-io/shesha-framework/issues/1258) of hidden humburger

z-index changed

---

shesha-reactjs/package.json
shesha-reactjs/src/designer-components/card/index.tsx
shesha-reactjs/src/designer-components/htmlRender/index.tsx
shesha-reactjs/src/designer-components/htmlRender/interfaces.ts
shesha-reactjs/src/designer-components/htmlRender/settingsForm.ts
shesha-reactjs/src/providers/form/defaults/toolboxComponents.ts

- Created Custom HTML Renderer
- [Link](https://github.com/shesha-io/shesha-framework/issues/1161)

Component render

---

shesha-reactjs/src/components/dataTable/cell/formCell/componentsContainerFormCell.tsx
shesha-reactjs/src/providers/parentProvider/index.tsx

An error occurred when you render most of the layout components within the custom subform renderer #1271

Fix containers for FormCell

---

shesha-core/src/Shesha.Framework/Migrations/M20240403165900.cs
shesha-reactjs/src/components/formDesigner/toolbar/canvasConfig.tsx
shesha-reactjs/src/components/formDesigner/toolbar/dialogButton.tsx
shesha-reactjs/src/providers/sheshaApplication/index.tsx

fixed migration M20240403165900

---

shesha-reactjs/src/components/fileUpload/stubs.tsx
shesha-reactjs/src/components/storedFilesRendererBase/styles/styles.ts

Addressed [issues](https://github.com/shesha-io/shesha-framework/issues/1261) related to icon and attachments color not updating dynamically.

applying primary color of icon

---

shesha-reactjs/src/components/formDesigner/formSettings.json

Adressed [issue](https://github.com/shesha-io/shesha-framework/issues/546) of duplication of 'InitialValues' variable onDataLoaded form settings

removed duplicate

---

shesha-functional-tests/publicportal/package-lock.json
shesha-functional-tests/publicportal/src/components/layouts/mainLayout/styles.ts
shesha-functional-tests/publicportal/src/styles/variables.ts
shesha-reactjs/src/designer-components/card/index.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json

- [Data Table Public Portal Styling](https://github.com/shesha-io/shesha-framework/issues/1192)
- [Hidden Card Bug](https://github.com/shesha-io/shesha-framework/issues/1289)
- [Duplicate CSS Property](https://github.com/shesha-io/shesha-framework/issues/1288)

Styling + Bug Fix

---

shesha-core/src/Shesha.Core/Localization/SourceFiles/Shesha-de.xml
shesha-core/src/Shesha.Core/Localization/SourceFiles/Shesha.xml

- added german localization source file
- fixed indent

add german locals & fix indent

---

shesha-core/src/Shesha.Application/Sessions/SessionAppService.cs

Linked issue: https://github.com/shesha-io/shesha-framework/issues/1247

Adding user Id to getCurrentLoginInfo endpoint

---

shesha-core/src/Shesha.Web.FormsDesigner/Migrations/M20240423163399.cs
shesha-reactjs/src/components/configurableForm/configurableFormRenderer.tsx
shesha-reactjs/src/components/debugPanel/dataContent.tsx
shesha-reactjs/src/components/debugPanel/dataTree.tsx
shesha-reactjs/src/components/debugPanel/index.tsx
shesha-reactjs/src/components/debugPanel/model.tsx
shesha-reactjs/src/components/formDesigner/components/formItem.tsx
shesha-reactjs/src/components/formDesigner/formSettings.json
shesha-reactjs/src/designer-components/_settings/settingsControl.tsx
shesha-reactjs/src/designer-components/dataContextComponent/index.tsx
shesha-reactjs/src/designer-components/dataContextComponent/settings.tsx
shesha-reactjs/src/designer-components/dropdown/settingsForm.json
shesha-reactjs/src/designer-components/htmlRender/settingsForm.ts
shesha-reactjs/src/generic-pages/dynamic/index.tsx
shesha-reactjs/src/generic-pages/forms-designer/index.tsx
shesha-reactjs/src/providers/dataContextManager/index.tsx
shesha-reactjs/src/providers/dataContextProvider/contexts.ts
shesha-reactjs/src/providers/dataContextProvider/dataContextBinder.tsx
shesha-reactjs/src/providers/dataContextProvider/index.tsx
shesha-reactjs/src/providers/dataTable/index.tsx
shesha-reactjs/src/providers/form/contexts.tsx
shesha-reactjs/src/providers/form/index.tsx
shesha-reactjs/src/providers/form/utils.ts
shesha-reactjs/src/providers/parentProvider/index.tsx
shesha-reactjs/src/utils/metadata/hooks.ts
shesha-reactjs/src/utils/metadata/standardProperties.tsx
shesha-reactjs/src/utils/metadata/useAvailableConstants.ts

Rename formContext to pageContext
Add async initialization for DataContext

FormContext does not append the data to the subform after selection on an autocomplete #1366

---

shesha-reactjs/src/designer-components/attachmentsEditor/settings.ts

Duplication of 'formMode' variable onFile List Changed #549

removed duplicate form mode property

---

shesha-core/src/Shesha.Web.FormsDesigner/Dtos/Forms/UpdateFormConfigurationDto.cs
shesha-core/src/Shesha.Web.FormsDesigner/Services/FormConfigurationAppService.cs

https://github.com/shesha-io/shesha-framework/issues/1318

Adding name property on formConfiguration update endpoint

---

shesha-reactjs/src/components/customFile/index.tsx
shesha-reactjs/src/components/storedFilesRendererBase/index.tsx

Addressed [issue](https://github.com/shesha-io/shesha-framework/issues/536), where FileList component allows file deletion when "Allow Remove" property is set to false.

hid delete icon

---

shesha-reactjs/src/providers/form/utils.ts

… created via execute script, those files do not get saved under that entity #1407

When files are attached to the fileList component before an entity is… #1407

---

shesha-core/src/Shesha.Core/Migrations/M20240501141100.cs
shesha-core/src/Shesha.Framework/Migrations/M20240501134700.cs

Permission CRUD endpoints throwing error when utilising #1424

Data discrepancies: Role View vs. Database #1425 #1424

---

shesha-reactjs/src/designer-components/entityPicker/index.tsx
shesha-reactjs/src/designer-components/entityPicker/settingsForm.ts
shesha-reactjs/src/designer-components/entityPicker/utils.ts

Added onChange event property on Entity Picker component, as requested on this [issue](https://github.com/shesha-io/shesha-framework/issues/851).

Thulasizwe/en/851 - onchange event for entity picker

---

shesha-core/src/Shesha.Application/ShaRoles/ShaRoleAppService.cs
shesha-core/src/Shesha.Framework/Authorization/ShaPermissionManager.cs
shesha-reactjs/src/components/configurableForm/configurableFormRenderer.tsx
shesha-reactjs/src/components/entityPicker/modal.tsx
shesha-reactjs/src/components/formDesigner/configurableFormComponent/dragWrapper.tsx
shesha-reactjs/src/components/permissionsTree/index.tsx
shesha-reactjs/src/designer-components/autocomplete/autocomplete.tsx
shesha-reactjs/src/designer-components/dataSource/dataSource.tsx
shesha-reactjs/src/designer-components/dataTable/tableViewSelector/tableViewSelector.tsx

Roles created are not displayed in Export Configuration Items #1434
Error thrown when deleting child permission after parent deletion #1436

Support for pageContext on query builder #1412

---

shesha-core/src/Shesha.Application/ConfigurationItems/ConfigurationItemAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host/Boxfusion.SheshaFunctionalTests.Web.Host.csproj
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host/Startup/Startup.cs
shesha-functional-tests/backend/test/Boxfusion.SheshaFunctionalTests.Common.Domain.Tests/Boxfusion.SheshaFunctionalTests.Common.Domain.Tests.csproj
shesha-reactjs/src/components/configurableForm/configurableFormRenderer.tsx
shesha-reactjs/src/components/formDesigner/formSettings.json
shesha-reactjs/src/generic-pages/dynamic/index.tsx
shesha-reactjs/src/providers/form/contexts.tsx
shesha-reactjs/src/providers/form/index.tsx
shesha-reactjs/src/providers/form/utils.ts
shesha-reactjs/src/providers/sheshaApplication/context/applicationContext.tsx
shesha-reactjs/src/utils/metadata/metadataBuilder.ts

refactoring of form events (handlers moved to form provider) fixed exposed constants on form events

configured Elmah logging to the DB for functional tests project

---

shesha-core/src/Shesha.Application/Permissions/Dtos/PermissionDto.cs
shesha-core/src/Shesha.Application/Permissions/PermissionAppService.cs
shesha-core/src/Shesha.Application/ShaRoles/Dto/CreateShaRoleDto.cs
shesha-core/src/Shesha.Application/ShaRoles/Dto/ShaRoleDto.cs
shesha-core/src/Shesha.Framework/Authorization/IShaPermissionManager.cs
shesha-core/src/Shesha.Framework/Authorization/ShaPermissionManager.cs
shesha-core/src/Shesha.Framework/ConfigurationItems/Distribution/ConfigurationPackageManager.cs
shesha-core/src/Shesha.Framework/ConfigurationItems/Distribution/IConfigurableItemImport.cs
shesha-core/src/Shesha.Framework/Permissions/Distribution/PermissionDefinitionImport.cs
shesha-core/src/Shesha.Framework/Services/ConfigurationItems/ConfigurationItemImportBase.cs
shesha-core/src/Shesha.Framework/Services/ReferenceLists/Distribution/ReferenceListImport.cs
shesha-reactjs/src/apis/permission.ts
shesha-reactjs/src/components/permissionAutocomplete/index.tsx
shesha-reactjs/src/components/permissionsTree/index.tsx
shesha-reactjs/src/components/permissionsTree/update-item-arguments.tsx
shesha-reactjs/src/designer-components/permissions/permissionAutocomplete/index.tsx
shesha-reactjs/src/providers/dataTable/filters/evaluateFilter.ts
shesha-reactjs/src/providers/form/defaults/toolboxComponents.ts

ImportPackage endpoint fail when importing permissions #1435

Create Permissions component that allows one or more permissions to be specified #693

---

shesha-reactjs/src/components/entityReference/index.tsx
shesha-reactjs/src/components/quickView/index.tsx
shesha-reactjs/src/designer-components/entityReference/entityReference.tsx

Addressed [issue](https://github.com/shesha-io/shesha-framework/issues/1432) regarding Entity Reference not displaying data when edit mode is set to readOnly or inherit, and [issue](https://github.com/shesha-io/shesha-framework/issues/545) regarding the style property not being reflected in on entity reference.

Thulasizwe/f/1432 : Entity Reference display data

---

shesha-core/src/Shesha.Framework/Domain/EntityChangeAuditLog.cs
shesha-core/src/Shesha.Framework/Migrations/M20240506174800.cs

Linked issue: https://github.com/shesha-io/shesha-framework/issues/1349

Updating audit log view to be able to filter on the frontend

---

shesha-reactjs/src/designer-components/dateField/datePickerWrapper.tsx

Hi @AlexStepantsov . Please kindly assist with this PR addressing the [issue here](https://github.com/shesha-io/shesha-framework/issues/1166).

mapped correct format instead of default

---

shesha-reactjs/src/components/formDesigner/formComponent.tsx
shesha-reactjs/src/components/permissionAutocomplete/index.tsx
shesha-reactjs/src/designer-components/button/buttonGroup/buttonGroupComponent.tsx
shesha-reactjs/src/designer-components/button/buttonGroup/models.ts
shesha-reactjs/src/designer-components/button/settingsForm.ts
shesha-reactjs/src/designer-components/dynamicView/dynamicComponent.tsx
shesha-reactjs/src/designer-components/permissions/permissionAutocomplete/index.tsx
shesha-reactjs/src/designer-components/tabs/models.ts
shesha-reactjs/src/designer-components/textField/settingsForm.json
shesha-reactjs/src/designer-components/wizard/models.ts
shesha-reactjs/src/designer-components/wizard/settings.tsx
shesha-reactjs/src/interfaces/toolbarSettings.ts
shesha-reactjs/src/providers/form/index.tsx
shesha-reactjs/src/providers/form/models.ts

base Permissions setting for IConfigurableFormComponent

When using the default buttons to attach files using the fileList component, the _delayedUpdate property is not appended #1444

---

shesha-functional-tests/publicportal/src/app/account/forgot-password/page.tsx
shesha-functional-tests/publicportal/src/app/account/forgot-password/styles.ts
shesha-functional-tests/publicportal/src/app/login/page.tsx
shesha-functional-tests/publicportal/src/app/login/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/loginPageLayout/styles.ts
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/button/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/input/index.tsx
shesha-functional-tests/publicportal/src/components/layouts/unAuthedAccountPageLayout/menu/index.tsx
shesha-functional-tests/publicportal/src/styles/global.ts
shesha-starter/publicportal/src/app/account/forgot-password/page.tsx
shesha-starter/publicportal/src/app/account/forgot-password/styles.ts
shesha-starter/publicportal/src/app/login/page.tsx
shesha-starter/publicportal/src/app/login/styles.ts
shesha-starter/publicportal/src/components/layouts/loginPageLayout/styles.ts
shesha-starter/publicportal/src/components/layouts/unAuthedAccountPageLayout/button/index.tsx
shesha-starter/publicportal/src/components/layouts/unAuthedAccountPageLayout/input/index.tsx
shesha-starter/publicportal/src/components/layouts/unAuthedAccountPageLayout/menu/index.tsx
shesha-starter/publicportal/src/styles/global.ts

- [Tags on Data Tables too large ](https://github.com/shesha-io/shesha-framework/issues/1457)
- [Table links font size smaller than other fields](https://github.com/shesha-io/shesha-framework/issues/1455)
- [FAQ screen updates](https://github.com/shesha-io/shesha-framework/issues/1453)
- [Search component spacing issue](https://github.com/shesha-io/shesha-framework/issues/1452)
- [Change icon to Hamburger menu with text](https://github.com/shesha-io/shesha-framework/issues/1450)
- [Forgot Password and Register in Dialogue boxes instead of a new screen](https://github.com/shesha-io/shesha-framework/issues/1449)
- [Set a max width for input fields on sign in screen](https://github.com/shesha-io/shesha-framework/issues/1448)
- [Remove 3rd party sign in's for …

Cosmetic Changes

---

shesha-core/src/Shesha.NHibernate.PostGis/Shesha.NHibernate.PostGis.csproj
shesha-core/test/Shesha.Tests/Metadata/MetadataProvider_Tests.cs

updated Npgsql and Npgsql.NetTopologySuite

---

shesha-reactjs/src/designer-components/divider/index.tsx
shesha-reactjs/src/designer-components/divider/settingsForm.json

related issue: https://github.com/shesha-io/shesha-framework/issues/574

removing unused settings from divider component

---

shesha-reactjs/src/components/reactTable/styles/styles.ts

Addresed [issue](https://github.com/shesha-io/shesha-framework/issues/563) where some text on selected row remained black instead of white.

white text

---

shesha-reactjs/src/components/dataList/styles/styles.ts

fixed datalist overflow

---

shesha-reactjs/src/components/debugPanel/dataTree.tsx
shesha-reactjs/src/components/debugPanel/debugDataTreeProp.tsx
shesha-reactjs/src/designer-components/dateField/datePickerWrapper.tsx

Datefield formatting (DD-MM-YYYY) data doesn't match endpoint data/what has been selected #1166

The payload sends the exact format received from the component which differs to what the backend is expecting #1468

---

shesha-reactjs/src/components/reactTable/tableRow.tsx
shesha-reactjs/src/designer-components/dateField/datePickerWrapper.tsx
shesha-reactjs/src/providers/form/utils.ts
shesha-reactjs/src/utils/date.ts

Dyanamic dateField filtering sends the incorrect format expected by the endpoint bug #1542
Date not selectable during inline editing when show time property is enabled bug urgent #1541
The payload sends the exact format received from the component which differs to what the backend is expecting bug urgent #1468
Datefield formatting (DD-MM-YYYY) data doesn't match endpoint data/what has been selected bug #1166

When 'show time' is false, current time should not be sent on the payload bug #1543

---

shesha-reactjs/src/components/notesRenderer/index.tsx
shesha-reactjs/src/components/notesRendererBase/index.tsx
shesha-reactjs/src/designer-components/notes/notesComponent.tsx
shesha-reactjs/src/designer-components/notes/settingsForm.json

Added 'allow delete' functionality to be a configuration on Notes component as requested on [issue](https://github.com/shesha-io/shesha-framework/issues/544).

allow delete ?

---

shesha-reactjs/src/designer-components/entityReference/settings.tsx

The related issue
https://github.com/shesha-io/shesha-framework/issues/1580
@OmolemoBlessingLethuloe

Use ButtonGroupConfigurator instead of ButtonGroupSettingsModal

---

shesha-reactjs/src/components/sidebarContainer/styles/styles.ts

Hi @AlexStepantsov . Please kindly assist with this PR addressing issue raised [here](https://github.com/shesha-io/shesha-framework/issues/1303).

allow both vertical and horizontal scroll

---

shesha-reactjs/src/components/entityConfigTree/index.tsx

removed debug text

---

shesha-reactjs/src/components/sidebarMenu/utils.tsx

fixed sidebar hard reload when using url navigation

---

shesha-reactjs/src/components/dataTable/cell/actionCell.tsx
shesha-reactjs/src/components/sidebarMenu/utils.tsx

fix for hard navigation when clicking action cell

---

shesha-reactjs/src/designer-components/button/configurableButton/index.tsx

fixed button crashing when query parameters are not configured

---

.github/CONTRIBUTING.md
README.md
shesha-reactjs/README.md
shesha-reactjs/package.json

> Also changed the title of CONTRIBUTING.md

Edited readme for npm, also changed the heading on CONTRIBUTING.md

---

shesha-reactjs/src/designer-components/_common-migrations/migrateFormApi1.ts
shesha-reactjs/src/generic-pages/dynamic/index.tsx

fixed antd warning on dynamic page

fixed form settings migration

---

shesha-reactjs/src/components/sidebarMenu/utils.tsx

#1711 
Removed default icon even when configuration is root

removed default icon even when component is root

---

shesha-reactjs/src/components/dataTable/cell/actionCell.tsx

changed no url tag from <span> to <a> tag

---

shesha-reactjs/src/components/keyInformationBar/index.tsx
shesha-reactjs/src/components/keyInformationBar/utils.ts
shesha-reactjs/src/designer-components/keyInformationBar/columnsList.tsx
shesha-reactjs/src/designer-components/keyInformationBar/settings.tsx

Key Information Bar : refactor

---

shesha-reactjs/src/components/notesRendererBase/styles/index.style.ts

Reduced height on the notes-card and added margin

Notes Card Styling

---

shesha-reactjs/src/components/sectionSeparator/index.tsx

Fixing issue with line not appearing on other components due to line thickness being null/undefined

fix: default line thickness

---

shesha-reactjs/src/designer-components/dataTable/advancedFilterButton/style.ts
shesha-reactjs/src/designer-components/dataTable/filterList/filterList.tsx

fixing the space between the filter items, clear all button and result text

fix: adding just a bit of space between filter items and (clear all button and result count)

---

shesha-reactjs/src/components/formDesigner/containers/componentsContainer.tsx
shesha-reactjs/src/designer-components/container/containerComponent.tsx

container background properties for stored file

---

shesha-reactjs/src/designer-components/text/genericText.tsx

Hi @IvanIlyichev . Please kindly have a look on this PR address issue raised [here](https://github.com/shesha-io/shesha-framework/issues/855) . I have just included the second scenario of an array with ' ' initially and didn't want to give default an actual value avoiding other unforeseen cases.

text color

---

shesha-reactjs/src/designer-components/container/settingsForm.ts

fixed invalid stored file value

---

shesha-reactjs/src/providers/auth/index.tsx

- [Admin portal initializes but does not navigate to intended URL upon signing in](https://github.com/shesha-io/shesha-framework/issues/1937)

Login Navigation Issues

---

shesha-reactjs/src/components/appConfigurator/styles/styles.ts
shesha-reactjs/src/designer-components/editModeToggler/index.tsx
shesha-reactjs/src/designer-components/profileDropdown/index.tsx
shesha-reactjs/src/designer-components/profileDropdown/settingsForm.ts
shesha-reactjs/src/designer-components/slider/index.tsx
shesha-reactjs/src/designer-components/slider/interfaces.ts
shesha-reactjs/src/designer-components/slider/settings.ts
shesha-reactjs/src/interfaces/toolbarSettings.ts
shesha-reactjs/src/providers/form/defaults/toolboxComponents.ts

- [Hidden/ Custom Visibility not working properly on public portal components](https://github.com/shesha-io/shesha-framework/issues/1894)

Custom Visibility

---

shesha-reactjs/src/components/configurableForm/formWithFlatMarkup.tsx

- [Hide form info when logged out](https://github.com/shesha-io/shesha-framework/issues/1893)

LoginInfo to formWithFlatMarkup

---

shesha-reactjs/src/components/dynamicModal/index.tsx
shesha-reactjs/src/generic-pages/dynamic/index.tsx
shesha-reactjs/src/providers/configurableActionsDispatcher/index.tsx
shesha-reactjs/src/providers/dynamicModal/index.tsx
shesha-reactjs/src/providers/dynamicModal/models.ts

form:refresh action throws error when used on stand-alone form/table #1928

Action Refresh table fails when used on custom buttons #1947

---

shesha-reactjs/src/designer-components/container/containerComponent.tsx
shesha-reactjs/src/designer-components/image/image.tsx
shesha-reactjs/src/designer-components/image/index.tsx

Base64 Image not rendering in Image component and container background property #1980

Attached image remains visible on UI after successful deletion #1983

---

shesha-reactjs/src/components/formDesigner/toolbar/mobileDropdown.tsx

Hi @Lukeybooi  @hlayisanimazuze  returned[ this card](https://github.com/shesha-io/shesha-framework/issues/1665) to have exact values as in the browser responsive tab. Please review and approve

adjusted mobile sizes

---

shesha-reactjs/src/designer-components/textField/textField.tsx

Hi @AlexStepantsov , Please kindly assist with this quick review on this [issue](https://github.com/shesha-io/shesha-framework/issues/2028).

password crash fix

---

shesha-reactjs/src/components/buttonGroupConfigurator/buttonGroupItem.tsx
shesha-reactjs/src/components/buttonGroupConfigurator/itemSettings.json
shesha-reactjs/src/designer-components/button/button.tsx
shesha-reactjs/src/designer-components/button/buttonGroup/buttonGroup.tsx
shesha-reactjs/src/designer-components/button/settingsForm.ts
shesha-reactjs/src/designer-components/dataTable/advancedFilterButton/advancedFilterButton.tsx
shesha-reactjs/src/providers/buttonGroupConfigurator/models.ts

This PR addresses all the issues raise on [issues](https://github.com/shesha-io/shesha-framework/issues/2038)

fix:  Button and Button Group impact layout and functionality #2038

---

shesha-reactjs/src/components/dataList/createModal.tsx

Hi @AlexStepantsov . Please assist with this PR addressing the issue raised [here](https://github.com/shesha-io/shesha-framework/issues/1932) . Please ignore the second issue regarding script , the script was just not correct. The CreateModal for dataList was overlook since it is a stand alone instead of using DynamicModal.

create modal button fix

---

shesha-reactjs/src/designer-components/card/index.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/collapsiblePanelComponent.tsx
shesha-reactjs/src/designer-components/columns/columns.tsx
shesha-reactjs/src/designer-components/keyInformationBar/index.tsx
shesha-reactjs/src/designer-components/sizableColumns/sizableColumns.tsx
shesha-reactjs/src/designer-components/tabs/index.tsx
shesha-reactjs/src/designer-components/wizard/index.tsx
shesha-reactjs/src/designer-components/wizard/tabs.tsx

This PR addresses [issue](https://github.com/shesha-io/shesha-framework/issues/2094) that requires an bottom margin for some layout components.

Thulasizwe/f/2094: Adding margin to some layout component (Card, Panels, Key Information Bar, Tabs)

---

shesha-reactjs/src/components/formDesigner/formSettings.json
shesha-reactjs/src/utils/metadata/typesBuilder.ts

updated form settings to use types endpoint result

code editor: added label and description to the generated return type

---

shesha-reactjs/src/utils/autocomplete.ts

Fixes type check that is failing on the build

[fix] Autocomplete util- accepted values to include string

---

shesha-reactjs/src/designer-components/charts/chartControl.tsx
shesha-reactjs/src/designer-components/charts/components/bar/index.tsx
shesha-reactjs/src/designer-components/charts/components/filterComponent/index.tsx
shesha-reactjs/src/designer-components/charts/components/line/index.tsx
shesha-reactjs/src/designer-components/charts/components/pie/index.tsx
shesha-reactjs/src/designer-components/charts/settings.ts
shesha-reactjs/src/designer-components/charts/styles.ts
shesha-reactjs/src/designer-components/charts/utils.ts

Standardised colors, CategoryScale error fix

Charts enhancements: Standardised colors, CategoryScale error fix

---

.gitignore
shesha-reactjs/next-env.d.ts
shesha-reactjs/src/components/configurableForm/configurableFormRenderer.tsx
shesha-reactjs/src/components/configurableForm/models.ts

added next-env.d.ts to ignore list

added showDataSubmitIndicator prop to the configurable form

---

shesha-reactjs/src/components/refListDropDown/genericRefListDropDown.tsx

use width from styles if width prop is undefined

---

shesha-reactjs/src/components/panel/index.tsx
shesha-reactjs/src/components/panel/styles/styles.ts
shesha-reactjs/src/designer-components/collapsiblePanel/collapsiblePanelComponent.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/interfaces.ts
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json

This is the relevant item
https://github.com/shesha-io/shesha-framework/issues/1899

configurable collapsible panel border radius

---

shesha-reactjs/src/designer-components/charts/chartControl.tsx
shesha-reactjs/src/designer-components/charts/chartControlURL.tsx
shesha-reactjs/src/designer-components/charts/components/bar/index.tsx
shesha-reactjs/src/designer-components/charts/components/line/index.tsx
shesha-reactjs/src/designer-components/charts/components/pie/index.tsx
shesha-reactjs/src/designer-components/charts/components/polarArea/index.tsx
shesha-reactjs/src/designer-components/charts/index.tsx
shesha-reactjs/src/designer-components/charts/model.ts
shesha-reactjs/src/designer-components/charts/settings.ts
shesha-reactjs/src/designer-components/charts/styles.ts
shesha-reactjs/src/designer-components/charts/utils.ts
shesha-reactjs/src/providers/chartData/actions.tsx
shesha-reactjs/src/providers/chartData/context.tsx
shesha-reactjs/src/providers/chartData/index.tsx
shesha-reactjs/src/providers/chartData/reducer.tsx

- URL data source
- evaluate query builder mustache for 'entityType' data source
- Refined component property settings

Charts enhancements

---

shesha-reactjs/src/designer-components/charts/chartControl.tsx
shesha-reactjs/src/designer-components/charts/chartControlURL.tsx
shesha-reactjs/src/designer-components/charts/components/bar/index.tsx
shesha-reactjs/src/designer-components/charts/components/line/index.tsx
shesha-reactjs/src/designer-components/charts/components/pie/index.tsx
shesha-reactjs/src/designer-components/charts/components/polarArea/index.tsx
shesha-reactjs/src/designer-components/charts/model.ts
shesha-reactjs/src/designer-components/charts/settings.ts
shesha-reactjs/src/designer-components/charts/utils.ts
shesha-reactjs/src/providers/chartData/context.tsx

- Bug fixed: Grouping by reflist property in a table (where some values are null was exlcuding the null data)
- Refined settings: added borderwidth for the different chart types
- Stricter null checks
- For cleaner code in the control components: passing the props directly to provider

Minor Enhancements + Bug fix

---

shesha-reactjs/src/components/configurableForm/formInfo.tsx

handle empty form props

---

shesha-reactjs/src/designer-components/text/genericText.tsx
shesha-reactjs/src/designer-components/text/typography.tsx

fix: changed the text component to have a key to force re-render.

---

shesha-reactjs/src/components/appConfigurator/editModeToggler.tsx
shesha-reactjs/src/components/configurableForm/formInfo.tsx
shesha-reactjs/src/components/configurableForm/styles/styles.ts
shesha-reactjs/src/providers/appConfigurator/actions.ts
shesha-reactjs/src/providers/appConfigurator/contexts.tsx
shesha-reactjs/src/providers/appConfigurator/index.tsx
shesha-reactjs/src/providers/appConfigurator/reducer.ts

removed conditional check before hiding formInfo panel

---

shesha-core/test/Shesha.Tests/UnitTestHelper.cs
shesha-reactjs/src/components/codeEditor/client-side/codeFiles.ts

mocked ISchemaGenerator in unit tests

code editor: fixed handling of result type

---

shesha-reactjs/src/designer-components/codeEditor/settingsForm.json
shesha-reactjs/src/providers/dynamicModal/configurable-actions/show-dialog-arguments.json

Code Editor: fixed function name for the Available Constants settings

Show Dialog action: changed type of arguments

---

shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.json

added max value to border radius

---

shesha-reactjs/src/designer-components/chevron/settings.tsx
shesha-reactjs/src/designer-components/kanban/settings.tsx
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/entityDynamicMenuItem/entitySettings.json
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/entityDynamicMenuItem/index.tsx
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/model.ts
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/urlDynamicMenuItem/index.tsx
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/urlDynamicMenuItem/urlSettings.json
shesha-reactjs/src/providers/refList/options/configurator.tsx

Fix for the following issues:
- #2387 
- #2385

Fix dynamic menu items

---

shesha-reactjs/src/providers/form/configurableActions/index.ts
shesha-reactjs/src/providers/form/index.tsx

Hi @IvanIlyichev .Please kindly assist with this PR addressing the issue raised [here](https://github.com/shesha-io/shesha-framework/issues/2393).

restore formData between toggle edit and cancel edit

---

shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/entityDynamicMenuItem/index.tsx
shesha-reactjs/src/providers/dynamicActions/implementations/dataSourceDynamicMenu/urlDynamicMenuItem/index.tsx

fix: The data not updating the state correctly

---

shesha-reactjs/src/providers/appConfigurator/index.tsx

Hi @AlexStepantsov , This PR addresses the issue raised [here](https://github.com/shesha-io/shesha-framework/issues/2388).

pass object instead of true

---

shesha-reactjs/src/components/dataTable/cell/default/stringCell.tsx
shesha-reactjs/src/components/displayFormItem/index.tsx
shesha-reactjs/src/components/mainLayout/index.tsx
shesha-reactjs/src/designer-components/charts/chartControl.tsx
shesha-reactjs/src/designer-components/charts/chartControlURL.tsx
shesha-reactjs/src/designer-components/charts/components/bar/index.tsx
shesha-reactjs/src/designer-components/charts/components/filterComponent/index.tsx
shesha-reactjs/src/designer-components/charts/components/line/index.tsx
shesha-reactjs/src/designer-components/charts/components/pie/index.tsx
shesha-reactjs/src/designer-components/charts/components/polarArea/index.tsx
shesha-reactjs/src/designer-components/charts/hooks.ts
shesha-reactjs/src/designer-components/charts/index.tsx
shesha-reactjs/src/designer-components/charts/model.ts
shesha-reactjs/src/designer-components/charts/settings.ts
shesha-reactjs/src/designer-components/charts/styles.ts
shesha-reactjs/src/designer-components/charts/utils.ts
shesha-reactjs/src/providers/chartData/context.tsx

- wrap the component in ConfigurableFormItem
- conditional wrap if the user is allowed to filter data directly on the chart
- generating titles in a hook to abstract away the code and reduce duplication while keeping chart type components simple
- refined settings to handle 'hidden' situations
- width that works interchangeably with width to preserve chart responsiveness
- util function to stringify values on render to avoid chart js errors with reflists and undefined values
- enable pie charts to turn into doughnuts
*Some screenshots*

Charts: enhancements and code optimisations

---

shesha-core/src/Shesha.Application/Sessions/Dto/UserLoginInfoDto.cs
shesha-core/src/Shesha.Application/Sessions/SessionAppService.cs
shesha-reactjs/src/apis/session.ts
shesha-reactjs/src/providers/sheshaApplication/context/applicationContext.tsx
shesha-reactjs/src/providers/sheshaApplication/publicApi/currentUser/api.ts
shesha-reactjs/src/providers/sheshaApplication/publicApi/currentUser/metadata.ts
shesha-reactjs/src/publicJsApis/userApi.ts

Add user.personId front-end API to get the current user's person id and utilize it in the code editor wherever `application` is exposed

Add user.personId front-end API to get the current user's person id

---

shesha-reactjs/src/components/notificationAutocomplete/index.tsx
shesha-reactjs/src/providers/dynamicActions/evaluator/index.tsx
shesha-reactjs/src/providers/dynamicActions/evaluator/singleDynamicItemEvaluator.tsx

changed entity type in the notification autocomplete

fixed dynamic evaluation of menu items

---

shesha-reactjs/src/designer-components/container/settingsForm.ts
shesha-reactjs/src/designer-components/image/image.tsx
shesha-reactjs/src/designer-components/image/index.tsx
shesha-reactjs/src/designer-components/image/settingsForm.json
shesha-reactjs/src/designer-components/imagePicker/index.tsx
shesha-reactjs/src/interfaces/toolbarSettings.ts

Related issue: #1788
Requested changes on the image type dropdown: replace "upload" with original "Base64" 
Added base64 image uploader to Container component
Restricted imagePicker to image selection only ( jpg, .png, .gif, .webp, .jpeg)

en: added base64 image uploader on container

---

shesha-core/src/Shesha.Application/README.md
shesha-core/src/Shesha.Application/Shesha.Application.csproj
shesha-core/src/Shesha.Common/README.md
shesha-core/src/Shesha.Common/Shesha.Common.csproj
shesha-core/src/Shesha.Core/README.md
shesha-core/src/Shesha.Core/Shesha.Core.csproj
shesha-core/src/Shesha.Elmah/README.md
shesha-core/src/Shesha.Elmah/Shesha.Elmah.csproj
shesha-core/src/Shesha.FluentMigrator/README.md
shesha-core/src/Shesha.FluentMigrator/Shesha.FluentMigrator.csproj
shesha-core/src/Shesha.Framework/README.md
shesha-core/src/Shesha.Framework/Shesha.Framework.csproj
shesha-core/src/Shesha.GraphQL/README.md
shesha-core/src/Shesha.GraphQL/Shesha.GraphQL.csproj
shesha-core/src/Shesha.Import/README.md
shesha-core/src/Shesha.Import/Shesha.Import.csproj
shesha-core/src/Shesha.MongoRepository/README.md
shesha-core/src/Shesha.MongoRepository/Shesha.MongoRepository.csproj
shesha-core/src/Shesha.NHibernate/README.md
shesha-core/src/Shesha.NHibernate/Shesha.NHibernate.csproj
shesha-core/src/Shesha.RestSharp/README.md
shesha-core/src/Shesha.RestSharp/Shesha.RestSharp.csproj
shesha-core/src/Shesha.Scheduler/README.md
shesha-core/src/Shesha.Scheduler/Shesha.Scheduler.csproj
shesha-core/src/Shesha.Sms.Clickatell/README.md
shesha-core/src/Shesha.Sms.Clickatell/Shesha.Sms.Clickatell.csproj
shesha-core/src/Shesha.Web.Core/README.md
shesha-core/src/Shesha.Web.Core/Shesha.Web.Core.csproj
shesha-core/src/Shesha.Web.FormsDesigner/README.md
shesha-core/src/Shesha.Web.FormsDesigner/Shesha.Web.FormsDesigner.csproj

The warnings when we run on local are disturbing, so I added the Package readmes to silence them
In accordance with package authoring best practices   
https://learn.microsoft.com/en-us/nuget/create-packages/package-authoring-best-practices#readme

chore: added Package README files

---

shesha-reactjs/src/components/entityReference/index.tsx

fixing display options, when referenceType is navigation-link

BugFix: entity-reference

---

shesha-reactjs/src/designer-components/refListStatus/index.tsx
shesha-reactjs/src/designer-components/refListStatus/models.ts
shesha-reactjs/src/designer-components/refListStatus/settings.ts

Hi @James-Baloyi , please have a look on the refList Status properties migration.

migrated reflistStatus

---

shesha-core/src/Shesha.Application/Notifications/Dto/SendStatus.cs
shesha-core/src/Shesha.Core/Domain/NotificationMessage.cs
shesha-core/src/Shesha.Framework/Domain/Attributes/MultiValueReferenceListAttribute.cs
shesha-core/src/Shesha.Framework/Domain/Attributes/ReferenceListAttribute.cs
shesha-core/src/Shesha.Framework/Migrations/M20250127102899.cs
shesha-core/src/Shesha.Sms.Clickatell/Clickatell/ClickatellSmsGateway.cs

Marked old constructors which contain namespaces as obsolete in MultiValueReferenceListAttribute and ReferenceListAttribute

Added SenderText and CC properties to NotificationMessage

---

shesha-reactjs/src/designer-components/profileDropdown/index.tsx
shesha-reactjs/src/designer-components/profileDropdown/settingsForm.ts

ft: updated ProfileDropdown component to include popOver functionality

ProfileDropdown Component Update

---

shesha-reactjs/src/designer-components/validationErrors/index.tsx
shesha-reactjs/src/designer-components/validationErrors/tabbedSettings.ts

Related issue https://github.com/shesha-io/shesha-framework/issues/2709

remove properties and turn off label

---

shesha-core/src/Shesha.Sms.Clickatell/Clickatell/ClickatellSmsGateway.cs

Linked Issue: https://github.com/shesha-io/shesha-framework/issues/2759

Adding support for handling multiple message parts from Clickatell

---

shesha-reactjs/src/designer-components/textArea/settingsForm.ts

Replace the dropdown for background-repeat with radio buttons.
addressing https://github.com/shesha-io/shesha-framework/issues/2664

radio button for background repeat options

---

shesha-core/src/Shesha.Application/Authorization/EntityCrudAuthorizationHelper.cs
shesha-core/src/Shesha.Application/DynamicCrudAppService.cs
shesha-core/src/Shesha.Application/DynamicEntities/EntitiesAppService.cs
shesha-core/src/Shesha.Application/Permissions/ApiPermissionedObjectProvider.cs
shesha-core/src/Shesha.Framework/Authorization/ObjectPermissionChecker.cs
shesha-core/src/Shesha.Framework/Domain/Attributes/CrudActionsAttribute.cs
shesha-core/src/Shesha.Framework/Domain/Attributes/CrudDisableActionsAttribute.cs
shesha-core/src/Shesha.Framework/Metadata/EntityModelProvider.cs
shesha-core/src/Shesha.Framework/Metadata/IMetadataProvider.cs
shesha-core/src/Shesha.Framework/Metadata/MetadataProvider.cs
shesha-core/src/Shesha.Framework/Permissions/EntityPermissionedObjectProvider.cs
shesha-core/src/Shesha.Framework/Permissions/PermissionedObjectManager.cs
shesha-core/src/Shesha.Framework/Permissions/PermissionedObjectProviderBase.cs
shesha-core/src/Shesha.Framework/Permissions/PermissionedObjectsBootstrapper.cs
shesha-core/src/Shesha.Framework/Swagger/SwaggerEndpointEnumerator.cs
shesha-functional-tests/backend/src/Module/Boxfusion.SheshaFunctionalTests.Common.Domain/Domain/Bus.cs
shesha-reactjs/src/components/modelConfigurator/permissionEditor/index.tsx
shesha-reactjs/src/components/modelConfigurator/permissionSettings.json

Support DisableCrudActions attribute on entities to allow #2682
Minor fix EntityModelProvider (nullable)

Support DisableCrudActions attribute on entities to allow #2682

---

shesha-reactjs/src/designer-components/_settings/settingsControl.tsx
shesha-reactjs/src/designer-components/_settings/utils/border/utils.tsx
shesha-reactjs/src/designer-components/container/settingsForm.ts
shesha-reactjs/src/designer-components/inputComponent/index.tsx
shesha-reactjs/src/designer-components/settingsInput/settingsInput.tsx

Reverts shesha-io/shesha-framework#2792

Revert "Properties panel code editor"

---

shesha-reactjs/src/designer-components/container/settingsForm.ts
shesha-reactjs/src/designer-components/image/image.tsx
shesha-reactjs/src/designer-components/image/index.tsx
shesha-reactjs/src/designer-components/image/settingsForm.ts

first commit: addressed issue - 2829

---

shesha-reactjs/src/designer-components/passwordCombo/index.tsx
shesha-reactjs/src/designer-components/passwordCombo/settingsForm.ts

https://github.com/shesha-io/shesha-framework/issues/2818

password combo jsstyle fix

---

shesha-core/src/Shesha.Application/Notifications/Emails/EmailChannelSender.cs
shesha-core/src/Shesha.Application/Notifications/INotificationSender.cs
shesha-core/src/Shesha.Application/Notifications/NotificationSender.cs
shesha-core/src/Shesha.Application/Notifications/NullNotificationSender.cs
shesha-core/src/Shesha.Core/Domain/NotificationMessage.cs
shesha-core/src/Shesha.Web.Host/Startup/Startup.cs
shesha-functional-tests/backend/Directory.Build.props
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/ActivateMembershipAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/BankMemberAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/BookAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/DynamicColumnsTest.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/NotificationTestAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/Persons/PersonTestAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/PlaygroundAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/SchoolAppService.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Core/Authorization/ISheshaFunctionalTestsPermissionChecker.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Core/Authorization/SheshaFunctionalTestsPermissionChecker.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Core/Boxfusion.SheshaFunctionalTests.Web.Core.xml
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Core/SheshaFunctionalTestsWebCoreModule.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host/Startup/AuthConfigurer.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Web.Host/Swagger/SwaggerDefaultValues.cs
shesha-functional-tests/backend/test/Boxfusion.SheshaFunctionalTests.Common.Domain.Tests/SheshaFunctionalTestsCommonDomainTestModule.cs

INotificationSender: changed nullability of the cc argurment
Shesha web project: enabled data annotations

enabled nullables for FunctionalTests web project

---

shesha-reactjs/src/designer-components/rate/index.tsx
shesha-reactjs/src/designer-components/rate/settingsForm.ts

https://github.com/shesha-io/shesha-framework/issues/2823

Addressing Issues on Rate

---

shesha-reactjs/src/designer-components/alert/index.tsx
shesha-reactjs/src/designer-components/alert/settingsForm.ts

https://github.com/shesha-io/shesha-framework/issues/2815

Addressing 42 related Alert issues

---

shesha-reactjs/src/designer-components/textArea/settingsForm.ts
shesha-reactjs/src/designer-components/textArea/textArea.tsx
shesha-reactjs/src/designer-components/textArea/utils.ts

https://github.com/shesha-io/shesha-framework/issues/2664

Textarea adjustments

---

shesha-reactjs/src/designer-components/validationErrors/index.tsx
shesha-reactjs/src/designer-components/validationErrors/tabbedSettings.ts

https://github.com/shesha-io/shesha-framework/issues/2822

Addressing issues on 42 with ValidationErrors component

---

shesha-reactjs/src/designer-components/button/util.ts
shesha-reactjs/src/designer-components/passwordCombo/index.tsx
shesha-reactjs/src/designer-components/passwordCombo/utils.ts
shesha-reactjs/src/designer-components/textField/utils.ts

adding defaults

---

shesha-reactjs/src/components/panel/index.tsx
shesha-reactjs/src/components/panel/styles/styles.ts
shesha-reactjs/src/designer-components/_settings/utils/border/utils.tsx
shesha-reactjs/src/designer-components/collapsiblePanel/settingsForm.ts
shesha-reactjs/src/designer-components/collapsiblePanel/utils.ts
shesha-reactjs/src/designer-components/columns/settingsForm.ts
shesha-reactjs/src/designer-components/numberField/settingsForm.ts
shesha-reactjs/src/designer-components/textArea/settingsForm.ts
shesha-reactjs/src/designer-components/textField/settingsForm.ts
shesha-reactjs/src/designer-components/wizard/utils.ts

fix: panel style causing error

addressed panel issue

---

shesha-starter/backend/src/ShaCompanyName.ShaProjectName.Web.Core/ShaProjectNameWebCoreModule.cs
shesha-starter/backend/src/ShaCompanyName.ShaProjectName.Web.Host/Startup/Startup.cs

fix: changed the useElmah to useSheshaElmah

---

shesha-core/README.md

- update shesha-core README license to mention Apache License 2.0 and point to repo root `LICENSE.md`
- `git status --short`

Update core README license section

---

shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/Dto/BulkNotificationDto.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/Dto/NotificationTestDto.cs
shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/NotificationTestAppService.cs

fix: changing the way we retrieve the files for better testing

---

shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/ChartsTestAppService.cs

https://github.com/shesha-io/shesha-framework/issues/3252#issuecomment-2980546545

Test Endpoint Action for charts

---

shesha-reactjs/src/components/notesRenderer/index.tsx
shesha-reactjs/src/components/notesRendererBase/index.tsx
shesha-reactjs/src/designer-components/notes/notesComponent.tsx
shesha-reactjs/src/designer-components/notes/settingsForm.ts

fix(notes): resolve event triggers and reorganize settings
- Fixed multiple "On Create" triggers by tracking added notes
- Added "On Delete" event to settings
- Hid delete icon during edit mode
- Moved validation settings to new tab and renamed fields
- Added min length validation with proper error messages
- Styled delete confirmation button with theme colors
- Renamed events and settings for consistency ("On Created" → "On Create", etc.)
**Issue**
https://github.com/shesha-io/shesha-framework/issues/3446

events handlers and settings arrangements of the note component

---

shesha-functional-tests/adminportal/src/app/app-provider.tsx

fix: fixing the build

---

shesha-functional-tests/backend/src/Boxfusion.SheshaFunctionalTests.Common.Application/Services/NotificationTestAppService.cs

This is for fixing the test cases for notifications on Shesha

fix: making sure schoolId is not null

---

shesha-reactjs/src/designer-components/textArea/textArea.tsx

https://github.com/shesha-io/shesha-framework/issues/3777

add characters counter

---

shesha-reactjs/src/designer-components/wizard/index.tsx

style migration

---

shesha-reactjs/src/configuration-studio/document-definitions/configurable-editor/index.tsx
shesha-reactjs/src/interfaces/toolbarSettings.ts
shesha-reactjs/src/providers/formDesigner/reducer.ts
shesha-reactjs/src/providers/referenceListDispatcher/index.tsx

fixed handling of immutable state in forms designer disabled logging of form events in configuration studio

fixed reference list related hooks
