shesha-io/shesha-framework

- shesha-reactjs/src/designer-components/timeField/index.tsx
- shesha-reactjs/src/pages/dynamic/index.stories.tsx
- shesha-reactjs/src/pages/forms-designer/index.stories.tsx
This is linked to [this issue](https://github.com/shesha-io/shesha-framework/issues/533). I only passed the default Date_time format to the readonly to make sure it align with the edit mode one.
> aligned the time-format to 24HR

- shesha-reactjs/src/components/sidebarContainer/styles/styles.ts
Hi @AlexStepantsov . On Friday I made a PR to allow all three parts of formDesigner to be independently scrollable , that worked. But it also made the height of all components that has "SidebarContainer" to all have height of 85vh hence[ this bug](https://github.com/shesha-io/shesha-framework/issues/981). Please kindly review and feedback. Thanks
> sidebarContainerMainAreaBody height fix

- shesha-reactjs/src/components/reactTable/styles/styles.ts
We have upgraded the dataTable to have some columns fixed on the left or right. So when the action column(s) are anchored
and you select a row we want the color to remain as primary color for better visibility since we don't change the background of those fixed columns.
> preserve  the icon/link color on selected when it is fixed

- shesha-reactjs/src/components/formDesigner/components/switch/switch.tsx
This pull request resolves https://github.com/shesha-io/shesha-framework/issues/665.
The issue was caused by the incorrect prop being used to pass the value of a read-only switch into the read-only component. There is also a small format fix on an existing line.
> Fix for the ready-only switch component.

- shesha-reactjs/src/components/entityPicker/index.tsx
- shesha-reactjs/src/components/formDesigner/components/entityPicker/index.tsx
I have addressed the sizing and styling issues of the entity picker, as reported in GitHub [Issues](https://github.com/shesha-io/shesha-framework/issues/576)
This PR ensures that the entity picker now adheres to the desired behavior, size and style dynamically adjust based on the specified settings.
> entityPicker dynamic size and style fix

- shesha-reactjs/src/components/formDesigner/components/dataList/dataListSettings.tsx
Changed "Form identifer expression" to "Form identifier expression" as per this issue https://github.com/shesha-io/shesha-framework/issues/1230
> Fixing spelling of word "Identifier"

- shesha-reactjs/src/components/formDesigner/components/button/buttonGroup/buttonGroup.tsx
Addressed the [issue](https://github.com/shesha-io/shesha-framework/issues/556) relating to button group not responding to space size.
> space size issue/556

- shesha-reactjs/src/components/formDesigner/components/codeEditor/codeEditor.tsx
Related to [this](https://github.com/shesha-io/shesha-framework/issues/1226) issue
> Reverting to default width of the code editor

- shesha-reactjs/src/designer-components/richTextEditor/index.tsx
Addressed [issue](https://github.com/shesha-io/shesha-framework/issues/1387) with Rich text editor component breaking when switching to JavaScript placeholder.
> Thulasizwe/f/1387: switching to JavaScript placeholder

- shesha-reactjs/src/components/reactTable/styles/styles.ts
Addressed the [issue](https://github.com/shesha-io/shesha-framework/issues/1533) where if a row is selected, the information texts become white, however when inline editing, the text remains white making it hard for user to see what they are editing
> visble text for row in edit mode

- shesha-reactjs/src/designer-components/tabs/index.tsx
- shesha-reactjs/src/designer-components/tabs/settings.tsx
This is connected to this issue:
https://github.com/shesha-io/shesha-framework/issues/1568
> Changed the default value of the edit mode of a tab item to inherited

- shesha-reactjs/src/hocs/withAuth.tsx
- shesha-reactjs/src/providers/auth/index.tsx
Essentially undoes the red pill fix #1763 to allow the provider to have time to read the local storage  on time, which this PR https://github.com/shesha-io/shesha-framework/pull/1763 prevents
Related issues:
- https://github.com/shesha-io/shesha-framework/issues/1768
- https://github.com/shesha-io/shesha-framework/issues/1769
> fix: View type reset on page reload

- shesha-reactjs/src/components/keyInformationBar/index.tsx
- shesha-reactjs/src/components/keyInformationBar/style.ts
- shesha-reactjs/src/components/keyInformationBar/utils.ts
- shesha-reactjs/src/designer-components/keyInformationBar/columnsList.tsx
- shesha-reactjs/src/designer-components/keyInformationBar/index.tsx
- shesha-reactjs/src/designer-components/keyInformationBar/interfaces.ts
- shesha-reactjs/src/designer-components/keyInformationBar/settings.tsx
I added the ability to  adjust the padding inside the column, revert to default height when the height property is empty/removed, alignment of the columns, by default the alignment of the columns are left aligned and leaves a huge space on the right. Can we have a flexibility to align the columns? If columns properties are used, it leaves a grey space
[issue](https://github.com/shesha-io/shesha-framework/issues/635#issuecomment-2210855613)
> Thulasizwe/en/635: Key information bar adjustments

- shesha-reactjs/src/components/sectionSeparator/index.tsx
- shesha-reactjs/src/components/sectionSeparator/styles/styles.ts
- shesha-reactjs/src/components/sectionSeparator/title.tsx
- shesha-reactjs/src/components/sectionSeparator/utils.ts
- shesha-reactjs/src/designer-components/sectionSeprator/index.tsx
- shesha-reactjs/src/designer-components/sectionSeprator/settings.ts
- Refining the title margin
-  Keeping the hint icon consistent (in size and color)
- Hidding non-applicable configs 
- Added migration to replace noMargin property with titleMargin
> Thulasizwe/en/1741: Section separator - clean up

- shesha-core/src/Shesha.FluentMigrator/FluentMigrator/Settings/SettingsDbHelper.cs
- shesha-core/src/Shesha.Framework/Settings/Attributes/SettingAttribute.cs
- shesha-core/src/Shesha.Framework/Settings/DynamicSettingDefinitionProvider.cs
SettingAttribute: added overloads to prevent crash at runtime when constructor signature mismatches
SettingsDbHelper: fixed GetSettingValueId
> DynamicSettingDefinitionProvider: skip settings not linked to modules

- shesha-reactjs/src/components/kanban/components/renderColumn.tsx
- shesha-reactjs/src/components/kanban/index.tsx
- shesha-reactjs/src/components/kanban/model.ts
- shesha-reactjs/src/components/kanban/styles/styles.ts
- shesha-reactjs/src/designer-components/kanban/settings.tsx
- Added `maxResultCount` as a setting to limit data fetching.
- Added width properties to the settings.
- Added the ability to allow deleting items.
- Fixed the caching issue with the edit form.
- Ensured that when `readOnly` is checked, items cannot be edited or deleted.
> Kanban Cleanups

- shesha-reactjs/src/designer-components/sizableColumns/sizableColumns.tsx
Hi @IvanIlyichev  . Please assist with this PR addressing the issue raised [here](https://github.com/shesha-io/shesha-framework/issues/1847). We have previous discussed it where we added up making use of key to ensure re-render  of 'SizableColumns' for accurate representation of the current columns.
> using key to force re-render

- shesha-reactjs/src/designer-components/charts/components/bar/index.tsx
- shesha-reactjs/src/designer-components/charts/components/line/index.tsx
- shesha-reactjs/src/designer-components/charts/components/pie/index.tsx
- shesha-reactjs/src/designer-components/charts/components/polarArea/index.tsx
- shesha-reactjs/src/designer-components/charts/settings.ts
- shesha-reactjs/src/designer-components/charts/utils.ts
- shesha-reactjs/src/providers/chartData/context.tsx
When the configurator selects that the chart should have a title but then they don't provide the title, the fallback title that shows should be the one that informs about the parameters of the chart
> Charts fallback title enhancements

- shesha-reactjs/src/designer-components/charts/chartControl.tsx
- shesha-reactjs/src/designer-components/charts/hooks.ts
- shesha-reactjs/src/designer-components/charts/utils.ts
> Bug fix for deeply nested chart properties
> 
> ![image](https://github.com/user-attachments/assets/30b2697f-a6e4-4391-9980-e5238364aa21)
must be 
> 
> ![image](https://github.com/user-attachments/assets/fcf68009-aed4-451f-9089-2a9e7bbd0b4b)
> 
> So that for example y-axis can be like so
> ![image](https://github.com/user-attachments/assets/e66b9e7b-7633-4006-a54e-71eff37d86bc)
> Faster reflist items stringification on fetching of data
> Standard colors for 'null', 'undefined' and adjacent words
> Chart enhancements + bug fix

- shesha-reactjs/src/components/formDesigner/designerMainArea/index.tsx
Also show scrollbar if the data in the form overflows in the designer that pops in the modal to allow the configurator to see the preview of the entire form as before
> chore: deselect the selected component when going into preview

- shesha-reactjs/src/components/formDesigner/componentPropertiesPanel/index.tsx
- shesha-reactjs/src/components/formDesigner/toolbox.tsx
When opening the form designer on the fly into the dialog, the dialog / modal imposes the height on its children. This is good. But now the overflowing content does not show properly.
> This PR adds 50px bottomPadding to each on the side panel contents so that they are rendered correctly without hiding other things
Before:
After:
> chore: padding-bottom 50px on side panels of the form designer

- shesha-core/README.md
- shesha-core/src/Shesha.Application/README.md
- shesha-core/src/Shesha.Common/README.md
- shesha-core/src/Shesha.Core/README.md
- shesha-core/src/Shesha.Elmah/README.md
- shesha-core/src/Shesha.FluentMigrator/README.md
- shesha-core/src/Shesha.Framework/README.md
- shesha-core/src/Shesha.GraphQL/README.md
- shesha-core/src/Shesha.Import/README.md
- shesha-core/src/Shesha.MongoRepository/README.md
- shesha-core/src/Shesha.NHibernate/README.md
- shesha-core/src/Shesha.RestSharp/README.md
- shesha-core/src/Shesha.Scheduler/README.md
- shesha-core/src/Shesha.Sms.Clickatell/README.md
- shesha-core/src/Shesha.Web.Core/README.md
- shesha-core/src/Shesha.Web.FormsDesigner/README.md
- Updates to the README files to have nuget versions for each class library   
- Added "how to run locally" for shesha-core solution on the shesha-core root README
- Updated the dead link to LICENSE on the shesha-core root README to point to the license on shesha-reactjs
> Updates to the markdown files + Update dead link to GPL 3 license on the repo

- shesha-core/src/Shesha.NHibernate/Migrations/M20250220151500.cs
Adding migration to increase string length for reciepientId column on  OtpAuditItems entity to account for longer recipientTexts.
Related issue: https://github.com/shesha-io/shesha-framework/issues/2537
> Adding migration to increase string length for reciepientId column

- shesha-reactjs/src/providers/mainMenu/index.tsx
Related issue: https://github.com/shesha-io/shesha-framework/issues/3196
`updateMenu` must be called when the user logs in (auth state changes) to decide on what must be on the menu
this forces the menu to be validated when the user los because `updateMenu` will call `getActualItemsModel` which will call `anyOfPermissionsGranted` to ensure only the items relevant to the user are shown on the menu
> fix the side menu hiding some items on login

- shesha-reactjs/src/components/attributeDecorator/index.tsx
- shesha-reactjs/src/designer-components/_settings/utils/overflow/util.tsx
Modified because the original code re-create children component twice (due to change Wrapper component to Fragment)
> Re-implement AttributeDecorator

- shesha-reactjs/src/designer-components/dynamicActionsConfigurator/genericSettingsEditor.tsx
After selecting the dynamic Entity Configuration, the label and tooltip properties become hidden when you move away from the button and then return to it
> Property panel adjustments for ButtonGroup component #2740
